# Generated by Django 5.2.4 on 2025-09-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_n_auth', '0002_alter_user_options_user_users_n_aut_email_4fcc00_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='withdrawal_wallet',
        ),
    ]
