# Generated by Django 5.2.4 on 2025-09-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_n_auth', '0003_remove_userprofile_withdrawal_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/sample.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
