# Generated by Django 5.2.4 on 2025-09-13 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('causes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='organizer_id',
            field=models.ForeignKey(help_text="References the organizer's user ID from the user-service.", on_delete=django.db.models.deletion.CASCADE, related_name='organized_causes', to=settings.AUTH_USER_MODEL),
        ),
    ]
