# Generated by Django 5.2.4 on 2025-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causes',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='ongoing', max_length=20),
        ),
    ]
