[build]
  command = "npm run build"
  publish = "build"

# API proxy must come BEFORE catch-all redirect
[[redirects]]
  from = "/api/*"
  to = "https://causehive-monolithic-production.up.railway.app/api/:splat"
  status = 200
  force = true

# Catch-all for SPA routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' https://js.paystack.co"
    Cache-Control = "public, max-age=31536000"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
