# Generated by Django 5.2.4 on 2025-09-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='email',
            field=models.EmailField(blank=True, help_text="Email address of the payment method ('anonymous')", max_length=254, null=True),
        ),
    ]
