name: CI

on:
  push:
    branches: [ main, newbranch ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --run
      - run: npm run build

  build-test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: causehive
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django checks
        env:
          SECRET_KEY: test
          DEBUG: 'True'
          DATABASE_URL: postgresql://user:pass@localhost:5432/causehive
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          PAYSTACK_SECRET_KEY: test
        run: |
          python manage.py check
      - name: Run tests
        env:
          SECRET_KEY: test
          DEBUG: 'True'
          DATABASE_URL: postgresql://user:pass@localhost:5432/causehive
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          PAYSTACK_SECRET_KEY: test
        run: |
          python manage.py test --noinput
